services:
  frontend:
    build: 
      context: ./vueseum-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/vueseum/frontend:/var/log/vueseum
      - /etc/letsencrypt/live/vueseum.io:/etc/letsencrypt/live/vueseum.io:ro
      - /etc/letsencrypt/archive/vueseum.io:/etc/letsencrypt/archive/vueseum.io:ro
    environment:
      - NODE_ENV=production
      - ORIGIN=https://vueseum.io
    networks:
      - vueseum-network
    depends_on:
      - backend

  backend:
    build: 
      context: ./vueseum
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - vueseum-network
      - container-subnet

networks:
  vueseum-network:
    driver: bridge
  container-subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.3.0/24
