services:
  frontend:
    build: 
      context: ./vueseum-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"  # Vite HMR
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ORIGIN=http://localhost:3000
      - VITE_API_URL=http://backend:8080
    volumes:
      - ./vueseum-frontend/src:/app/src
      - ./vueseum-frontend/static:/app/static
      - ./vueseum-frontend/package.json:/app/package.json
      - ./vueseum-frontend/svelte.config.js:/app/svelte.config.js
      - ./vueseum-frontend/vite.config.ts:/app/vite.config.ts
      - ./vueseum-frontend/tsconfig.json:/app/tsconfig.json
      - ./vueseum-frontend/node_modules/@sveltejs:/app/node_modules/@sveltejs
    networks:
      - vueseum-network

  backend:
    build: 
      context: ./vueseum
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/artplatform
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - LOGGING_CONFIG=classpath:log4j2-dev.xml
      - SPRING_CONFIG_IMPORT=classpath:aiprovider.properties,classpath:museum.properties,classpath:visitor.properties
      - SPRING_CLOUD_AZURE_KEYVAULT_SECRET_ENABLED=false
      - SPRING_CLOUD_AZURE_ENABLED=false
      - AI_OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./vueseum/src:/app/src  # Only mount the src directory for live development
      - ./vueseum/target:/app/target  # Mount target directory for build outputs
      - ~/.m2:/root/.m2
    networks:
      - vueseum-network

networks:
  vueseum-network:
    driver: bridge
