name: Deploy Backend to Azure VM

on:
  push:
    branches: [ "master" ]
    paths:
      - 'vueseum/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:     

concurrency:
  group: "backend-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vueseum
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Transfer and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Create base64 of just the JAR file
            DEPLOY_PACKAGE=$(base64 -w 0 ./vueseum/target/*.jar)
            
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "
                # Clean and prepare directory
                sudo rm -rf /opt/vueseum/backend/*
                sudo mkdir -p /opt/vueseum/backend
                
                # Copy Dockerfile
                sudo cat > /opt/vueseum/backend/Dockerfile << 'EOF'
                $(cat ${{ github.workspace }}/vueseum/Dockerfile)
                EOF
                
                # Decode and save the JAR
                echo '$DEPLOY_PACKAGE' | base64 -d | sudo tee /opt/vueseum/backend/app.jar >/dev/null
                
                # Set permissions
                sudo chown -R vueseum:vueseum /opt/vueseum/backend
                sudo chmod -R 755 /opt/vueseum/backend
                sudo chmod 644 /opt/vueseum/backend/app.jar

                # Run deployment script
                cd /opt/vueseum && sudo ./deploy-containers.sh
                "
