name: Deploy Frontend to Azure VM

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:     

concurrency:
  group: "vm-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vueseum/vueseum-frontend
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Transfer and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Create storage account if it doesn't exist
            az storage account create \
              --name vueseumdeploy \
              --resource-group vueseum-prod-rg \
              --sku Standard_LRS \
              --kind StorageV2 \
              2>/dev/null || true

            # Create temporary container
            CONTAINER_NAME="deploy-$(date +%s)"
            az storage container create \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login

            # Change this part in the workflow
            az storage blob upload-batch \
              --account-name vueseumdeploy \
              --source ./.svelte-kit/output \
              --destination $CONTAINER_NAME \
              --auth-mode login

            # Generate SAS token for the container
            END_TIME=$(date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ')
            SAS_TOKEN=$(az storage container generate-sas \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --permissions r \
              --expiry $END_TIME \
              --auth-mode login \
              --as-user \
              --output tsv)

            # Get container URL
            CONTAINER_URL=$(az storage container url \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --output tsv)

            # Create temp directory and deploy on VM
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "
                mkdir -p /tmp/deploy
                
                # Download build files using curl
                cd /tmp/deploy
                curl -O '${CONTAINER_URL}?${SAS_TOKEN}'
                
                if [ -d /tmp/deploy ]; then
                  # Run deployment script
                  cd /opt/vueseum && ./deploy-frontend.sh /tmp/deploy
                  rm -rf /tmp/deploy
                  systemctl is-active vueseum-frontend || echo 'Service check failed'
                else
                  echo 'Build files not found'
                  exit 1
                fi"

            # Cleanup: Delete container
            az storage container delete \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login
