name: Deploy Frontend to Azure VM

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vueseum/vueseum-frontend
        
    steps:
      - uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -R

      - name: Debug - Print Working Directory
        run: pwd
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache-dependency-path: 'vueseum/vueseum-frontend/package-lock.json'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
          
      - name: Build
        run: npm run build
        env:
          # Adding environment variables for production build
          VITE_API_URL: 'https://vueseum.io/api'
          NODE_ENV: 'production'
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Deploy to VM
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Create temporary directory
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts 'mkdir -p /tmp/frontend-deploy'
            
            # Copy build files to VM
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "sudo cp -r ./build/* /tmp/frontend-deploy/"
            
            # Run frontend deployment script
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts 'cd /opt/vueseum && sudo -u vueseum ./deploy-frontend.sh /tmp/frontend-deploy'
            
            # Cleanup
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts 'rm -rf /tmp/frontend-deploy'
      
      - name: Verify Deployment
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Simple curl check to verify the site is responding
            curl -I https://vueseum.io
