name: Deploy Backend to Azure VM

on:
  push:
    branches: [ "master" ]
    paths:
      - 'vueseum/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:     

concurrency:
  group: "backend-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vueseum
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Transfer and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Find the JAR file
            JAR_FILE=$(find ${{ github.workspace }}/vueseum/target -name "*.jar" -type f)
            
            # Create storage account if it doesn't exist
            az storage account create \
              --name vueseumdeploy \
              --resource-group vueseum-prod-rg \
              --sku Standard_LRS \
              --kind StorageV2 \
              2>/dev/null || true

            # Create temporary container
            CONTAINER_NAME="deploy-$(date +%s)"
            az storage container create \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login

            # Upload JAR
            az storage blob upload \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name vueseum.jar \
              --file "$JAR_FILE" \
              --auth-mode login

            # Generate SAS token
            END_TIME=$(date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ')
            BLOB_URL=$(az storage blob url \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name vueseum.jar \
              --output tsv)
            SAS_TOKEN=$(az storage blob generate-sas \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name vueseum.jar \
              --permissions r \
              --expiry $END_TIME \
              --auth-mode login \
              --as-user \
              --output tsv)

            # Deploy to VM
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "
                sudo mkdir -p /tmp/deploy
                sudo curl -o /tmp/deploy/vueseum.jar '${BLOB_URL}?${SAS_TOKEN}'
                
                if [ -f /tmp/deploy/vueseum.jar ]; then
                  sudo mkdir -p /opt/vueseum/backend
                  sudo mv /tmp/deploy/vueseum.jar /opt/vueseum/backend/app.jar
                  
                  # Create Dockerfile
                  sudo tee /opt/vueseum/backend/Dockerfile << 'EOF'
                  FROM eclipse-temurin:21-jre
                  
                  WORKDIR /app
                  COPY app.jar .
                  
                  EXPOSE 8080
                  CMD [\"java\", \"-jar\", \"app.jar\"]
                  EOF
                  
                  sudo chown -R vueseum:vueseum /opt/vueseum/backend
                  sudo chmod 644 /opt/vueseum/backend/app.jar
                  sudo chmod 644 /opt/vueseum/backend/Dockerfile
                  sudo chmod 755 /opt/vueseum/backend
                  
                  cd /opt/vueseum && sudo ./deploy-containers.sh
                  rm -rf /tmp/deploy
                fi"

            # Cleanup: Delete temporary container
            az storage container delete \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login
