name: Deploy Frontend to Azure VM

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:     

concurrency:
  group: "vm-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Directory Structure
        run: |
          echo "Current directory: $PWD"
          echo "Repository root: ${{ github.workspace }}"
          echo "Directory contents:"
          ls -la
          echo "Full directory tree:"
          tree -L 2
        working-directory: ${{ github.workspace }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Transfer and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Create storage account if it doesn't exist
            az storage account create \
              --name vueseumdeploy \
              --resource-group vueseum-prod-rg \
              --sku Standard_LRS \
              --kind StorageV2 \
              2>/dev/null || true

            # Create temporary container
            CONTAINER_NAME="deploy-$(date +%s)"
            az storage container create \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login

            # Upload build files as single archive
            cd ${{ github.workspace }}/vueseum-frontend/.svelte-kit/output
            tar -czf build.tar.gz *
            
            # Upload archive
            az storage blob upload \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name build.tar.gz \
              --file build.tar.gz \
              --auth-mode login

            # Generate SAS token for the specific blob
            END_TIME=$(date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ')
            SAS_TOKEN=$(az storage blob generate-sas \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name build.tar.gz \
              --permissions r \
              --expiry $END_TIME \
              --auth-mode login \
              --as-user \
              --output tsv)

            # Get blob URL
            BLOB_URL=$(az storage blob url \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name build.tar.gz \
              --output tsv)

            # Create temp directory, download and deploy on VM
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "
                mkdir -p /tmp/deploy
                cd /tmp/deploy
                curl -o build.tar.gz '${BLOB_URL}?${SAS_TOKEN}'
                tar -xzf build.tar.gz
                
                if [ -d /tmp/deploy ]; then
                  cd /opt/vueseum && ./deploy-frontend.sh /tmp/deploy
                  rm -rf /tmp/deploy
                  systemctl is-active vueseum-frontend || echo 'Service check failed'
                else
                  echo 'Build files not found'
                  exit 1
                fi"

            # Cleanup: Delete container
            az storage container delete \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login
