name: Deploy Backend to Azure VM

on:
  push:
    branches: [ "master" ]
    paths:
      - 'vueseum/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:     

concurrency:
  group: "backend-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vueseum
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Transfer and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Debug: Show current location and structure
            pwd
            ls -la
            
            # Find the JAR file
            JAR_FILE=$(find ${{ github.workspace }}/vueseum/target -name "*.jar" -type f)
            if [ -z "$JAR_FILE" ]; then
              echo "No JAR file found in target directory"
              ls -la ./target  # Debug: show contents of target directory
              exit 1
            fi
            echo "Found JAR file: $JAR_FILE"

            # Create storage account if it doesn't exist
            az storage account create \
              --name vueseumdeploy \
              --resource-group vueseum-prod-rg \
              --sku Standard_LRS \
              --kind StorageV2 \
              2>/dev/null || true

            # Create temporary container
            CONTAINER_NAME="deploy-$(date +%s)"
            az storage container create \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login

            # Upload JAR
            echo "Uploading JAR to blob storage..."
            az storage blob upload \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name vueseum.jar \
              --file "$JAR_FILE" \
              --auth-mode login

            # Generate SAS token for the specific blob
            END_TIME=$(date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ')
            BLOB_URL=$(az storage blob url \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name vueseum.jar \
              --output tsv)
            SAS_TOKEN=$(az storage blob generate-sas \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name vueseum.jar \
              --permissions r \
              --expiry $END_TIME \
              --auth-mode login \
              --as-user \
              --output tsv)

            # Deploy to VM
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "
                set -x  # Enable command tracing
                
                # Create temp directory for deployment
                sudo mkdir -p /tmp/deploy
                echo '[Deploy] Created temp directory'
                ls -la /tmp/deploy
                
                # Download JAR using curl and SAS token
                echo '[Deploy] Attempting to download JAR file...'
                sudo curl -v -o /tmp/deploy/vueseum.jar '${BLOB_URL}?${SAS_TOKEN}'
                
                echo '[Deploy] Checking downloaded file'
                ls -la /tmp/deploy
                
                if [ -f /tmp/deploy/vueseum.jar ]; then
                  echo '[Deploy] JAR file downloaded successfully'
                  
                  echo '[Deploy] Current backend directory contents:'
                  ls -la /opt/vueseum/backend/
                  
                  # Update backend directory
                  sudo mkdir -p /opt/vueseum/backend
                  sudo rm -rf /opt/vueseum/backend/*
                  
                  echo '[Deploy] Moving JAR file...'
                  sudo mv -v /tmp/deploy/vueseum.jar /opt/vueseum/backend/app.jar
                  
                  echo '[Deploy] Setting permissions...'
                  sudo chown -R vueseum:vueseum /opt/vueseum/backend
                  sudo chmod 644 /opt/vueseum/backend/app.jar
                  sudo chmod 755 /opt/vueseum/backend
                  
                  echo '[Deploy] Final backend directory contents:'
                  ls -la /opt/vueseum/backend/
                  
                  # Run deployment
                  cd /opt/vueseum && sudo ./deploy-containers.sh
                  
                  # Clean up temp directory
                  rm -rf /tmp/deploy
                  echo '[Deploy] Deployment completed'
                else
                  echo '[Deploy] ERROR: JAR file not found in /tmp/deploy'
                  ls -la /tmp/deploy
                  find /tmp/deploy -type f -exec file {} \;
                  exit 1
                fi"

            # Cleanup: Delete temporary container
            az storage container delete \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login
