name: Deploy Frontend to Azure VM

on:
  push:
    branches: [ "master" ]
    paths:
      - 'vueseum-frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:     

concurrency:
  group: "frontend-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vueseum-frontend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './vueseum-frontend/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      # Debug step to verify build output
      - name: Verify build output
        run: |
          echo "Checking build directory contents:"
          ls -la build/
          
      - name: Create deployment archive
        run: |
          echo "Creating deployment archive..."
          tar -czf frontend-deploy.tar.gz \
            src/ \
            build/ \
            package*.json \
            svelte.config.js \
            vite.config.ts \
            tsconfig.json \
            tailwind.config.ts \
            postcss.config.js \
            Dockerfile
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Transfer and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Debug: Show current location and structure
            pwd
            ls -la
            
            # Verify archive exists
            if [ ! -f ./vueseum-frontend/frontend-deploy.tar.gz ]; then
              echo "Deployment archive not found"
              exit 1
            fi
            echo "Found deployment archive"

            # Create storage account if it doesn't exist
            az storage account create \
              --name vueseumdeploy \
              --resource-group vueseum-prod-rg \
              --sku Standard_LRS \
              --kind StorageV2 \
              2>/dev/null || true

            # Create temporary container with timestamp
            CONTAINER_NAME="frontend-deploy-$(date +%s)"
            az storage container create \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login

            # Upload archive
            az storage blob upload \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name frontend-deploy.tar.gz \
              --file ./vueseum-frontend/frontend-deploy.tar.gz \
              --auth-mode login

            # Generate SAS token
            END_TIME=$(date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ')
            BLOB_URL=$(az storage blob url \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name frontend-deploy.tar.gz \
              --output tsv)
            SAS_TOKEN=$(az storage blob generate-sas \
              --account-name vueseumdeploy \
              --container-name $CONTAINER_NAME \
              --name frontend-deploy.tar.gz \
              --permissions r \
              --expiry $END_TIME \
              --auth-mode login \
              --as-user \
              --output tsv)

            # Deploy to VM
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "
                # Create temp directory for deployment
                sudo mkdir -p /tmp/deploy
                
                # Download archive using curl and SAS token
                echo 'Downloading deployment archive...'
                sudo curl -o /tmp/deploy/frontend-deploy.tar.gz '${BLOB_URL}?${SAS_TOKEN}'
                
                if [ -f /tmp/deploy/frontend-deploy.tar.gz ]; then
                  echo 'Deployment archive downloaded successfully'
                  
                  # Update frontend directory
                  sudo mkdir -p /opt/vueseum/frontend
                  sudo rm -rf /opt/vueseum/frontend/*
                  
                  # Extract archive
                  cd /opt/vueseum/frontend
                  sudo tar xzf /tmp/deploy/frontend-deploy.tar.gz
                  
                  # Set permissions
                  sudo chown -R vueseum:vueseum /opt/vueseum/frontend
                  sudo chmod 644 /opt/vueseum/frontend/Dockerfile
                  sudo chmod 644 /opt/vueseum/frontend/package*.json
                  sudo chmod 644 /opt/vueseum/frontend/svelte.config.js
                  sudo chmod -R 755 /opt/vueseum/frontend/build
                  
                  # Run deployment
                  cd /opt/vueseum && sudo ./deploy-containers.sh
                  
                  # Cleanup
                  sudo rm -rf /tmp/deploy
                else
                  echo 'Deployment archive not found after download'
                  exit 1
                fi"

            # Cleanup: Delete temporary container
            az storage container delete \
              --account-name vueseumdeploy \
              --name $CONTAINER_NAME \
              --auth-mode login
