name: Deploy Frontend to Azure VM

on:
  push:
    branches: [ "master" ]
    paths:
      - 'vueseum-frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:     

concurrency:
  group: "frontend-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vueseum-frontend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './vueseum-frontend/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      - name: Create deployment archive
        run: tar -czf frontend-deploy.tar.gz build/ package*.json svelte.config.js Dockerfile docker-entrypoint.sh nginx.conf
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Transfer and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Convert the tar.gz to base64 for transfer
            DEPLOY_PACKAGE=$(base64 -w 0 ./vueseum-frontend/frontend-deploy.tar.gz)
            
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "
                # Clean old files and create directory
                sudo rm -rf /opt/vueseum/frontend/*
                sudo mkdir -p /opt/vueseum/frontend
                
                # Decode and extract the deployment package
                echo '$DEPLOY_PACKAGE' | base64 -d | sudo tee /opt/vueseum/frontend/frontend-deploy.tar.gz >/dev/null
                cd /opt/vueseum/frontend && sudo tar xzf frontend-deploy.tar.gz
                sudo rm frontend-deploy.tar.gz
                
                # Set permissions
                sudo chown -R vueseum:vueseum /opt/vueseum/frontend
                sudo chmod -R 755 /opt/vueseum/frontend
                sudo chmod +x /opt/vueseum/frontend/docker-entrypoint.sh

                # Run deployment script
                cd /opt/vueseum && sudo ./deploy-containers.sh
                "
