name: Deploy Backend to Azure VM

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:      # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vueseum  # backend directory
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Deploy to VM
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Create a temporary directory for the JAR
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts 'mkdir -p /tmp/deploy'
      
            # Copy the JAR file to VM using az storage copy
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "sudo cp target/*.jar /tmp/deploy/vueseum.jar"
      
            # Run deployment script with the copied JAR
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts 'cd /opt/vueseum && sudo -u vueseum ./deploy.sh /tmp/deploy/vueseum.jar'
      
            # Cleanup
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts 'rm -rf /tmp/deploy'                  
