name: Deploy Backend to Azure VM

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:     

concurrency:
  group: "vm-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vueseum
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Transfer and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Find the JAR file
            JAR_FILE=$(find ${{ github.workspace }}/vueseum/target -name "*.jar" -type f)
            if [ -z "$JAR_FILE" ]; then
              echo "No JAR file found in target directory"
              ls -la ./target
              exit 1
            fi
            
            # Convert JAR to base64 for transfer
            ENCODED_JAR=$(base64 -w 0 "$JAR_FILE")
            
            # Deploy using Run Command
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "
                # Create temp directory
                mkdir -p /tmp/deploy
                
                # Decode and save JAR
                echo '$ENCODED_JAR' | base64 -d > /tmp/deploy/vueseum.jar
                
                if [ -f /tmp/deploy/vueseum.jar ]; then
                  # Run deployment script
                  cd /opt/vueseum && ./deploy-backend.sh /tmp/deploy/vueseum.jar
                  rm -rf /tmp/deploy
                  systemctl is-active vueseum-backend.service || echo 'Service check failed'
                else
                  echo 'JAR file not found after transfer'
                  exit 1
                fi"
