name: Update Docker Compose Configuration

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker-compose.prod.yml'
      - '.github/workflows/update-compose.yml'
  workflow_dispatch:

jobs:
  update-compose:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Update Compose File and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts '
                cat > /opt/vueseum/docker-compose.prod.yml << "COMPOSE_EOF"
                '"$(cat ${{ github.workspace }}/docker-compose.prod.yml)"'
                COMPOSE_EOF

                chown vueseum:vueseum /opt/vueseum/docker-compose.prod.yml
                chmod 644 /opt/vueseum/docker-compose.prod.yml

                cd /opt/vueseum && ./deploy-containers.sh
              '
