name: Update Docker Compose Configuration

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker-compose.prod.yml'
      - '.github/workflows/update-compose.yml'
  workflow_dispatch:

jobs:
  update-compose:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Copy Compose File to VM
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Create temporary file with compose content
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "echo '$(cat ${{ github.workspace }}/docker-compose.prod.yml)' > /opt/vueseum/docker-compose.prod.yml"

      - name: Set Permissions and Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az vm run-command invoke \
              --resource-group vueseum-prod-rg \
              --name vueseum-app-prod \
              --command-id RunShellScript \
              --scripts "
                chown vueseum:vueseum /opt/vueseum/docker-compose.prod.yml
                chmod 644 /opt/vueseum/docker-compose.prod.yml
                cd /opt/vueseum && ./deploy-containers.sh
              "
